---
- name: AWS Hybrid Cloud Connectivity
  hosts: localhost
  gather_facts: false

  # module_defaults:
  #   community.aws.ec2_vpc_vpn:
  #     region: us-east-1
  #     tags:
  #       Project: hybrid-connectivity

  vars:
    vpc_vpn:
      vpn_gateway_id: vgw-0ed6d96c66dcccea0b
      static_only: true

  tasks:
    # - name: Create a VPC VPN connection using vpc_vpn variable